/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class moe_leekcake_live2dforjvm_framework_jni_id_CubismIdJNI */

#ifndef _Included_moe_leekcake_live2dforjvm_framework_jni_id_CubismIdJNI
#define _Included_moe_leekcake_live2dforjvm_framework_jni_id_CubismIdJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     moe_leekcake_live2dforjvm_framework_jni_id_CubismIdJNI
 * Method:    GetString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_moe_leekcake_live2dforjvm_framework_jni_id_CubismIdJNI_GetString
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
