/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class moe_leekcake_live2dforjvm_MemoryAccessJNI */

#ifndef _Included_moe_leekcake_live2dforjvm_MemoryAccessJNI
#define _Included_moe_leekcake_live2dforjvm_MemoryAccessJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     moe_leekcake_live2dforjvm_MemoryAccessJNI
 * Method:    allocate
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_moe_leekcake_live2dforjvm_MemoryAccessJNI_allocate
  (JNIEnv *, jclass, jint);

/*
 * Class:     moe_leekcake_live2dforjvm_MemoryAccessJNI
 * Method:    allocateAligned
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_moe_leekcake_live2dforjvm_MemoryAccessJNI_allocateAligned
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     moe_leekcake_live2dforjvm_MemoryAccessJNI
 * Method:    writeToMemory
 * Signature: (JI[BII)V
 */
JNIEXPORT void JNICALL Java_moe_leekcake_live2dforjvm_MemoryAccessJNI_writeToMemory
  (JNIEnv *, jclass, jlong, jint, jbyteArray, jint, jint);

/*
 * Class:     moe_leekcake_live2dforjvm_MemoryAccessJNI
 * Method:    deAllocate
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_moe_leekcake_live2dforjvm_MemoryAccessJNI_deAllocate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     moe_leekcake_live2dforjvm_MemoryAccessJNI
 * Method:    deAllocateAligned
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_moe_leekcake_live2dforjvm_MemoryAccessJNI_deAllocateAligned
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
