/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class moe_leekcake_live2dforjvm_framework_jni_CubismFrameworkJNI */

#ifndef _Included_moe_leekcake_live2dforjvm_framework_jni_CubismFrameworkJNI
#define _Included_moe_leekcake_live2dforjvm_framework_jni_CubismFrameworkJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     moe_leekcake_live2dforjvm_framework_jni_CubismFrameworkJNI
 * Method:    StartUp
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_moe_leekcake_live2dforjvm_framework_jni_CubismFrameworkJNI_StartUp
  (JNIEnv *, jclass);

/*
 * Class:     moe_leekcake_live2dforjvm_framework_jni_CubismFrameworkJNI
 * Method:    CleanUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_moe_leekcake_live2dforjvm_framework_jni_CubismFrameworkJNI_CleanUp
  (JNIEnv *, jclass);

/*
 * Class:     moe_leekcake_live2dforjvm_framework_jni_CubismFrameworkJNI
 * Method:    IsStarted
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_moe_leekcake_live2dforjvm_framework_jni_CubismFrameworkJNI_IsStarted
  (JNIEnv *, jclass);

/*
 * Class:     moe_leekcake_live2dforjvm_framework_jni_CubismFrameworkJNI
 * Method:    Initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_moe_leekcake_live2dforjvm_framework_jni_CubismFrameworkJNI_Initialize
  (JNIEnv *, jclass);

/*
 * Class:     moe_leekcake_live2dforjvm_framework_jni_CubismFrameworkJNI
 * Method:    Dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_moe_leekcake_live2dforjvm_framework_jni_CubismFrameworkJNI_Dispose
  (JNIEnv *, jclass);

/*
 * Class:     moe_leekcake_live2dforjvm_framework_jni_CubismFrameworkJNI
 * Method:    IsInitialized
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_moe_leekcake_live2dforjvm_framework_jni_CubismFrameworkJNI_IsInitialized
  (JNIEnv *, jclass);

/*
 * Class:     moe_leekcake_live2dforjvm_framework_jni_CubismFrameworkJNI
 * Method:    GetIdManager
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_moe_leekcake_live2dforjvm_framework_jni_CubismFrameworkJNI_GetIdManager
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
