/* DO NOT EDIT THIS FILE - it is machine generated */
#include "moe_leekcake_live2dforjvm_Live2DCubismGLRenderingJNI.h"
#include <Live2DCubismGlRendering.h>

/*
 * Class:     moe_leekcake_live2dforjvm_Live2DCubismGLRenderingJNI
 * Method:    getSizeofGlRenderer
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_moe_leekcake_live2dforjvm_Live2DCubismGLRenderingJNI_getSizeofGlRenderer
(JNIEnv * env, jclass obj, jlong model) {
    return (jlong) csmGetSizeofGlRenderer( (const csmModel*) model );
}

/*
* Class:     moe_leekcake_live2dforjvm_Live2DCubismGLRenderingJNI
* Method:    makeGlRendererInPlace
* Signature: (JJJ)J
*/
JNIEXPORT jlong JNICALL Java_moe_leekcake_live2dforjvm_Live2DCubismGLRenderingJNI_makeGlRendererInPlace
(JNIEnv * env, jclass obj, jlong model, jlong address, jlong size) {
    return (jlong) csmMakeGlRendererInPlace((const csmModel*) model, (void*)address, size);
}

/*
* Class:     moe_leekcake_live2dforjvm_Live2DCubismGLRenderingJNI
* Method:    releaseGlRenderer
* Signature: (J)J
*/
JNIEXPORT void JNICALL Java_moe_leekcake_live2dforjvm_Live2DCubismGLRenderingJNI_releaseGlRenderer
(JNIEnv * env, jclass obj, jlong renderer) {
    csmReleaseGlRenderer((csmGlRenderer*) renderer);
}

/*
* Class:     moe_leekcake_live2dforjvm_Live2DCubismGLRenderingJNI
* Method:    updateGlRenderer
* Signature: (J)V
*/
JNIEXPORT void JNICALL Java_moe_leekcake_live2dforjvm_Live2DCubismGLRenderingJNI_updateGlRenderer
(JNIEnv * env, jclass obj, jlong renderer) {
    csmUpdateGlRenderer((csmGlRenderer*) renderer);
}

/*
* Class:     moe_leekcake_live2dforjvm_Live2DCubismGLRenderingJNI
* Method:    drawGl
* Signature: (JFJ)V
*/
JNIEXPORT void JNICALL Java_moe_leekcake_live2dforjvm_Live2DCubismGLRenderingJNI_drawGl
(JNIEnv * env, jclass obj, jlong renderer, jfloat mvp, jlong textures) {
    csmGlDraw((csmGlRenderer) renderer, mvp, textures);
}
