/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class moe_leekcake_live2dforjvm_Live2DCubismGLRenderingJNI */

#ifndef _Included_moe_leekcake_live2dforjvm_Live2DCubismGLRenderingJNI
#define _Included_moe_leekcake_live2dforjvm_Live2DCubismGLRenderingJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     moe_leekcake_live2dforjvm_Live2DCubismGLRenderingJNI
 * Method:    getSizeofGlRenderer
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_moe_leekcake_live2dforjvm_Live2DCubismGLRenderingJNI_getSizeofGlRenderer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     moe_leekcake_live2dforjvm_Live2DCubismGLRenderingJNI
 * Method:    makeGlRendererInPlace
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_moe_leekcake_live2dforjvm_Live2DCubismGLRenderingJNI_makeGlRendererInPlace
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     moe_leekcake_live2dforjvm_Live2DCubismGLRenderingJNI
 * Method:    releaseGlRenderer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_moe_leekcake_live2dforjvm_Live2DCubismGLRenderingJNI_releaseGlRenderer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     moe_leekcake_live2dforjvm_Live2DCubismGLRenderingJNI
 * Method:    updateGlRenderer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_moe_leekcake_live2dforjvm_Live2DCubismGLRenderingJNI_updateGlRenderer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     moe_leekcake_live2dforjvm_Live2DCubismGLRenderingJNI
 * Method:    drawGl
 * Signature: (J[FJ)V
 */
JNIEXPORT void JNICALL Java_moe_leekcake_live2dforjvm_Live2DCubismGLRenderingJNI_drawGl
  (JNIEnv *, jclass, jlong, jfloatArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
