/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class moe_leekcake_live2dforjvm_framework_jni_extend_ExtendPALJNI */

#ifndef _Included_moe_leekcake_live2dforjvm_framework_jni_extend_ExtendPALJNI
#define _Included_moe_leekcake_live2dforjvm_framework_jni_extend_ExtendPALJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     moe_leekcake_live2dforjvm_framework_jni_extend_ExtendPALJNI
 * Method:    bindProxy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_moe_leekcake_live2dforjvm_framework_jni_extend_ExtendPALJNI_bindProxy
  (JNIEnv *, jclass);

/*
 * Class:     moe_leekcake_live2dforjvm_framework_jni_extend_ExtendPALJNI
 * Method:    updateTime
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_moe_leekcake_live2dforjvm_framework_jni_extend_ExtendPALJNI_updateTime
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
