/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class moe_leekcake_live2dforjvm_framework_jni_extend_ExtendPALJNI_TextureProvider */

#ifndef _Included_moe_leekcake_live2dforjvm_framework_jni_extend_ExtendPALJNI_TextureProvider
#define _Included_moe_leekcake_live2dforjvm_framework_jni_extend_ExtendPALJNI_TextureProvider
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
