/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class moe_leekcake_live2dforjvm_framework_jni_effect_CubismBreathJNI_BreathParameterData */

#ifndef _Included_moe_leekcake_live2dforjvm_framework_jni_effect_CubismBreathJNI_BreathParameterData
#define _Included_moe_leekcake_live2dforjvm_framework_jni_effect_CubismBreathJNI_BreathParameterData
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
